package common.ServerInterfacePackage;


/**
* common/ServerInterfacePackage/timeSlotsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Wednesday, October 20, 2021 10:11:46 o'clock AM EDT
*/

abstract public class timeSlotsHelper
{
  private static String  _id = "IDL:common/ServerInterface/timeSlots:1.0";

  public static void insert (org.omg.CORBA.Any a, common.Timeslot[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static common.Timeslot[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = common.TimeslotHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (common.ServerInterfacePackage.timeSlotsHelper.id (), "timeSlots", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static common.Timeslot[] read (org.omg.CORBA.portable.InputStream istream)
  {
    common.Timeslot value[] = null;
    int _len0 = istream.read_long ();
    value = new common.Timeslot[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = common.TimeslotHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, common.Timeslot[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      common.TimeslotHelper.write (ostream, value[_i0]);
  }

}
