package common.ServerInterfacePackage;


/**
* common/ServerInterfacePackage/timeSlotsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Wednesday, October 20, 2021 10:11:46 o'clock AM EDT
*/

public final class timeSlotsHolder implements org.omg.CORBA.portable.Streamable
{
  public common.Timeslot value[] = null;

  public timeSlotsHolder ()
  {
  }

  public timeSlotsHolder (common.Timeslot[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = common.ServerInterfacePackage.timeSlotsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    common.ServerInterfacePackage.timeSlotsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return common.ServerInterfacePackage.timeSlotsHelper.type ();
  }

}
