package common;

/**
* common/CampusIDHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Wednesday, October 20, 2021 10:11:46 o'clock AM EDT
*/

public final class CampusIDHolder implements org.omg.CORBA.portable.Streamable
{
  public common.CampusID value = null;

  public CampusIDHolder ()
  {
  }

  public CampusIDHolder (common.CampusID initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = common.CampusIDHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    common.CampusIDHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return common.CampusIDHelper.type ();
  }

}
