package common;


/**
* common/ServerInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Wednesday, October 20, 2021 10:11:46 o'clock AM EDT
*/


//Interface for the Campus Server
public interface ServerInterfaceOperations 
{

  //		accounts getAllCustomerAccount();
  int getLocalAvailableTimeSlot ();

  //ADMIN ONLY
  String createRoom (String adminID, short roomNumber, String date, common.Timeslot[] listOfTimeSlots);
  String deleteRoom (String adminID, short roomNumber, String date, common.Timeslot[] listOfTimeSlots);

  //STUDENT ONLY
  String bookRoom (String studentID, common.CampusID campusID, short roomNumber, String date, common.Timeslot timeSlot);
  String getAvailableTimeSlot (String date);
  String cancelBooking (String studentID, String bookingID);
  String changeReservation (String bookingId, common.CampusID newCampusName, short newRoomNo, common.Timeslot newTimeSlot);
  int getUDPPort ();
  String getUDPHost ();
  void shutdown ();
} // interface ServerInterfaceOperations
