package common;


/**
* common/ServerInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Wednesday, October 20, 2021 9:34:37 o'clock PM EDT
*/


//Interface for the Campus Server
public abstract class ServerInterfacePOA extends org.omg.PortableServer.Servant
 implements common.ServerInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getLocalAvailableTimeSlot", new java.lang.Integer (0));
    _methods.put ("createRoom", new java.lang.Integer (1));
    _methods.put ("deleteRoom", new java.lang.Integer (2));
    _methods.put ("bookRoom", new java.lang.Integer (3));
    _methods.put ("getAvailableTimeSlot", new java.lang.Integer (4));
    _methods.put ("cancelBooking", new java.lang.Integer (5));
    _methods.put ("changeReservation", new java.lang.Integer (6));
    _methods.put ("getUDPPort", new java.lang.Integer (7));
    _methods.put ("getUDPHost", new java.lang.Integer (8));
    _methods.put ("shutdown", new java.lang.Integer (9));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  //		accounts getAllCustomerAccount();
       case 0:  // common/ServerInterface/getLocalAvailableTimeSlot
       {
         int $result = (int)0;
         $result = this.getLocalAvailableTimeSlot ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }


  //ADMIN ONLY
       case 1:  // common/ServerInterface/createRoom
       {
         String adminID = in.read_string ();
         short roomNumber = in.read_short ();
         String date = in.read_string ();
         common.Timeslot listOfTimeSlots[] = common.ServerInterfacePackage.timeSlotsHelper.read (in);
         String $result = null;
         $result = this.createRoom (adminID, roomNumber, date, listOfTimeSlots);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // common/ServerInterface/deleteRoom
       {
         String adminID = in.read_string ();
         short roomNumber = in.read_short ();
         String date = in.read_string ();
         common.Timeslot listOfTimeSlots[] = common.ServerInterfacePackage.timeSlotsHelper.read (in);
         String $result = null;
         $result = this.deleteRoom (adminID, roomNumber, date, listOfTimeSlots);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }


  //STUDENT ONLY
       case 3:  // common/ServerInterface/bookRoom
       {
         String studentID = in.read_string ();
         common.CampusID campusID = common.CampusIDHelper.read (in);
         short roomNumber = in.read_short ();
         String date = in.read_string ();
         common.Timeslot timeSlot = common.TimeslotHelper.read (in);
         String $result = null;
         $result = this.bookRoom (studentID, campusID, roomNumber, date, timeSlot);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // common/ServerInterface/getAvailableTimeSlot
       {
         String date = in.read_string ();
         String $result = null;
         $result = this.getAvailableTimeSlot (date);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // common/ServerInterface/cancelBooking
       {
         String studentID = in.read_string ();
         String bookingID = in.read_string ();
         String $result = null;
         $result = this.cancelBooking (studentID, bookingID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // common/ServerInterface/changeReservation
       {
         String studentID = in.read_string ();
         String bookingId = in.read_string ();
         common.CampusID newCampusName = common.CampusIDHelper.read (in);
         short newRoomNo = in.read_short ();
         common.Timeslot newTimeSlot = common.TimeslotHelper.read (in);
         String $result = null;
         $result = this.changeReservation (studentID, bookingId, newCampusName, newRoomNo, newTimeSlot);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // common/ServerInterface/getUDPPort
       {
         int $result = (int)0;
         $result = this.getUDPPort ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 8:  // common/ServerInterface/getUDPHost
       {
         String $result = null;
         $result = this.getUDPHost ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 9:  // common/ServerInterface/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:common/ServerInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ServerInterface _this() 
  {
    return ServerInterfaceHelper.narrow(
    super._this_object());
  }

  public ServerInterface _this(org.omg.CORBA.ORB orb) 
  {
    return ServerInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class ServerInterfacePOA
