package common;


import java.util.Objects;

/**
* common/Timeslot.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Wednesday, October 20, 2021 10:11:46 o'clock AM EDT
*/

public final class Timeslot implements org.omg.CORBA.portable.IDLEntity
{
  public int start = (int)0;
  public int end = (int)0;

  public Timeslot ()
  {
  } // ctor

  public Timeslot (int _start, int _end)
  {
    start = _start;
    end = _end;
  } // ctor

  @Override
  public String toString() {
    return "Timeslot{" +
            "start=" + start +
            ", end=" + end +
            '}';
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;
    Timeslot timeslot = (Timeslot) o;
    return start == timeslot.start &&
            end == timeslot.end;
  }

  @Override
  public int hashCode() {
    return Objects.hash(start, end);
  }
} // class Timeslot
