package common;


/**
* common/Timeslot.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Wednesday, October 20, 2021 10:11:46 o'clock AM EDT
*/

public final class Timeslot implements org.omg.CORBA.portable.IDLEntity
{
  public int start = (int)0;
  public int end = (int)0;

  public Timeslot ()
  {
  } // ctor

  public Timeslot (int _start, int _end)
  {
    start = _start;
    end = _end;
  } // ctor

} // class Timeslot
